### ISSUE TITLE
How to set proxy for gitbook editor in windows?

### ISSUE THREAD

**Issue by xosuperpig** [GitbookIO/editor-legacy#226] opened 2016-03-30 02:06 UTC
is there a config file for it ?

**Comment by yewang15215** [comment] 2017-03-01 07:47
same here

**Comment by joaquintoral** [comment] 2017-03-29 23:50
Same here.

**Comment by AaronO** [comment] 2017-03-30 09:57
@joaquintoral This is a duplicate of https://github.com/GitbookIO/feedback/issues/407

This repo is no longer active and only exists for archival purposes.

**Closed by AaronO** 2017-03-30 09:57 UTC
